// ===================== Enums in java ===================

Background :-
    -> payment status --> success, failed, pending
        class PaymentStatus{
            public static final int SUCCESS = 1;
            public static final int FAILED = 2;
            public static final int PENDING = 3;
        }

    -> Problem :-
            1. Type Safety : PaymentStatus.SUCCESS = 100 can create runtime error.
            2. Poor readability
            3. No grouping of related entity like PaymentStatus.SUCCESS == Role.ADMIN 


    -> enums is Enumerations
    -> it is predefined set of constant.
    -> introduce after java 5.

    -> Each Enum is Class 
    -> extens Enum class
    -> each constant are static & final
    -> objects of type Direction(define enum type)
    -> constructor are private so that no object can create of direction except 4 direction.

⭕  Internally working:-
            enum Direction{
                NORTH,
                SOUTH,
                EAST,
                WEST;  // notes at last add semicolon.
            }

    ==>>    final class Direction extends Enum<Direction>{
                public static final Direction NORTH = new Direction();
                public static final Direction SOUTH = new Direction();
                public static final Direction EAST = new Direction();
                public static final Direction WEST = new Direction();

                private Direction(){

                }
            }
    
    ==>     Memory management:-
            - four object of NORTH, SOUTH, EAST, WEST,  are created in heap only.
            - No further object of direction cannot create due to private constructor.
            - Metaspace of static Memory contain references
            - if Direction d = Direction.NORTH; this will create new references in stack that point to same object in heaps
            
⭕ think enum is class so it should have feature of class also like states & behaviours.
    -> yes it have lets understand it by example like each direction have specific degree.

    Eg:-
        enum Direction{
                NORTH(0),
                SOUTH(90),
                EAST(180),
                WEST(270);  

                private int degree;
                Direction(int degree){
                    this.degree = degree;
                }
                public int getDegree(){
                    return this.degree;
                }
        }

    compiler generated :-
            final class Direction extends Enum<Direction>{
                public static final Direction NORTH = new Direction(0);
                public static final Direction SOUTH = new Direction(90);
                public static final Direction EAST = new Direction(180);
                public static final Direction WEST = new Direction(270);

                private int degree;
                private Direction(int degree){
                    this.degree = degree;
                }
                public int getDegree(){
                    return this.degree;
                }
            }
    
    Let suppose each direction move in specific steps y-1,y+1,x+1,x-1; how do it.
                        move() (abstract) with anonymous class
                     /  /    \  \
                    (x-1) (y-1) (y+1) (x+1)
    Eg:-
            enum Direction{
                NORTH{
                    @Override
                    public void move(){
                        System.out.println("Move Up : y-1")
                    }
                },
                SOUTH{
                    @Override
                    public void move(){
                        System.out.println("Move down : y+1")
                    }
                },
                EAST{
                    @Override
                    public void move(){
                        System.out.println("Move right : x+1")
                    }
                },
                WEST{
                    @Override
                    public void move(){
                        System.out.println("Move left : x-1")
                    }
                };

                public abstract void move(); // we need to override this in subclass of NORTH,SOUTH,EAST,WEST but they are object, we know that anonymous class with object are used to override these kind of things.
            }

⭕ Enum class methods. from java.lang
        |-> values()            -- generated by compiler
        |-> valueOf(string)     -- generated by compiler
        |-> name()              -- given by enum class
        |-> ordinal()           -- given by enum class

    1. values() :- return array of enum constant for iteration.
        eg :-
            Direction[] directions = Direction.values();
            for(Direction d:directions){
                System.out.print(d.name() + ', '); // NORTH, SOUTH, EAST, WEST,

            }

    2. valueOf() :- convert a String into an enum constant
        -> valueOf argument are case sensitive if not match then throws illegalArgument exception.
        eg:-
            Direction d = Direction.valueOf("EAST");
            d.name()// EAST
    
    3. name() :- return name of constant
        -> if return string value of constant then name() vs toString();
            -> name() method can not be override but toString() can override to change default behaviour.

    4. ordinal() :- intially constant in enum are index from 0. then to access index ordinal are used.
        eg:-    
            Direction d = Direction.EAST;
            System.out.println(d.ordinal()); // 2 

⭕ Extra in depth :-
    - 
        final class Direction extends Enum<Direction>{
            /*------------------
                    rest as previous
                    -----------------------
            */
           private static final Direction[] $VALUES = {NORTH, SOUTH, EAST, WEST};

           public static Direction[] values(){
                return $VALUES.clone(); // clone to prevent original array modification.
           }

           public static Direction valueOf(string s){
                return super.valueOf(Direction.class,s); // here super referenc to Enum class.
           }
        }
    
    # when used
        - week of day
        - payment status
        - order status
        - logs(info, error, debug)
        